#!/bin/sh
#
# Generate a version string for use when building.
#
# * If RELEASE exists, and is non-empty, use the contents of that file.
#   This is in case we're building from a tarball.

if [ -s "RELEASE" ]; then
    cat RELEASE
else
    git describe --always
fi
