=pod

=head1 NAME

munin-node-c - a single binary implementing the node functionality

=head1 DESCRIPTION

The munin-node-c binary can handle a single connection to a Munin node on stdin and stdout.
It is usually run from an inetd like superserver.

=head1 OPTIONS

=over

=item B<-d> I<plugin_directory>

Specify the directory used to look up plugins.
This directory usually contains symbolic links to installed plugins and executable scripts.
The plugins are executed on request by the client to retrieve statistics about the system.

=item B<-e>

Enable extension stripping.
When this option is given, filename extensions in plugins are ignored.
This option is mainly useful on operating systems where extensions are relevant for execution.

=item B<-H> I<hostname>

Specify the hostname with which the node should greet clients.

=back

=head1 AUTHORS

Helmut Grohne, Steve Schnepp

=cut
